export interface State {
  start(): void;
  pause(): void;
  resume(): void;
  stop(): void;
  reset(): void;
  setSpeed(speed: number): void;
  setAlgorithm(algorithm: number): void;
  setHeuristic(heuristic: number): void;
  setDiagonal(diagonal: boolean): void;
  setMaze(maze: number): void;

  //   setWeight(weight: number): void;
  //   setPathfinding(pathfinding: boolean): void;
  //   setSorting(sorting: boolean): void;
  //   setMazeGeneration(mazeGeneration: boolean): void;
  //   setPathfindingModel(model: any): void;
  //   setSortingModel(model: any): void;
  //   setMazeModel(model: any): void;
  //   setSearchingModel(model: any): void;
  //   setSortingAlgorithm(algorithm: number): void;
  //   setSortingSpeed(speed: number): void;
  //   setSortingData(data: number[]): void;
  //   setSearchingData(data: number[]): void;
  //   setMazeData(data: number[]): void;
  //   setSearchingElement(element: number): void;
  //   setSearchingSpeed(speed: number): void;
  //   setMazeSpeed(speed: number): void;
  //   setMazeAlgorithm(algorithm: number): void;
  //   setSortingElement(element: number): void;
  //   setSortingPathfinding(pathfinding: boolean): void;
  //   setSearchingPathfinding(pathfinding: boolean): void;
  //   setMazePathfinding(pathfinding: boolean): void;
  //   setSortingSorting(sorting: boolean): void;
  //   setSearchingSorting(sorting: boolean): void;
  //   setMazeSorting(sorting: boolean): void;
  //   setSortingMazeGeneration(mazeGeneration: boolean): void;
  //   setSearchingMazeGeneration(mazeGeneration: boolean): void;
  //   setMazeMazeGeneration(mazeGeneration: boolean): void;
  //   setSortingMaze(maze: number): void;
  //   setSearchingMaze(maze: number): void;
  //   setMazeMaze(maze: number): void;
  //   setSortingPathfindingModel(model: any): void;
  //   setSearchingPathfindingModel(model: any): void;
  //   setMazePathfindingModel(model: any): void;
  //   setSortingSortingModel(model: any): void;
  //   setSearchingSortingModel(model: any): void;
  //   setMazeSortingModel(model: any): void;
  //   setSortingMazeModel(model: any): void;
}
